service: aws-lambda-crud-node
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  timeout: 5

functions:
  get-starship:
    handler: src/functions/get-starship.getStarship
    events:
      - httpApi:
          path: /starships/
          method: get
  post-starship:
    handler: src/functions/post-starship.postStarship
    events:
      - httpApi:
          path: /starships/
          method: post

plugins:
  - serverless-offline
  - serverless-event-body-option
