service: aws-zoluxiones-api
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2

functions:
  get-starship:
    handler: src/getStarship.getStarship
    events:
      - httpApi:
          path: /starships
          method: get
  post-starship:
    handler: src/postStarship.postStarship
    events:
      - httpApi:
          path: /starships
          method: post

plugins:
  - serverless-offline